# /ops/docker-compose.yml
version: "3.9"

name: unienroll

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=unienroll
      - RABBITMQ_DEFAULT_PASS=unienroll
      - RABBITMQ_DEFAULT_VHOST=/
      - TZ=Asia/Manila
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Mgmt UI http://localhost:15672 (unienroll/unienroll)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mssql_data:
  redis_data:
