-- Idempotent DB options
IF DB_ID('UniEnroll') IS NULL
BEGIN
  PRINT 'Creating database UniEnroll';
  DECLARE @sql nvarchar(max) = N'CREATE DATABASE [UniEnroll]';
  EXEC(@sql);
END
GO
ALTER DATABASE [UniEnroll] SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE [UniEnroll] SET ALLOW_SNAPSHOT_ISOLATION ON;
GO
